[workspace]
resolver = "1"
members = [
    "example_secrets",
    "hello_world",
    "set_pico_w_led",
    "web_sockets"
]

[workspace.dependencies]
cortex-m-rt = "0.7.3"
cyw43 = { version = "0.1.0", features = ["firmware-logs"] }
cyw43-pio = "0.1.0"
embassy-executor = { version = "0.5.0", features = ["arch-cortex-m", "executor-thread", "integrated-timers", "nightly"] }
embassy-futures = "0.1.1"
embassy-net = { version = "0.4.0", features = ["tcp", "proto-ipv4", "medium-ethernet"] }
embassy-rp = { version = "0.1.0", features = ["critical-section-impl", "time-driver"] }
embassy-sync = "0.5.0"
embassy-time = "0.3.0"
embassy-usb-logger = "0.1.0"
embedded-io-async = "0.6.0"
log = { version = "0.4.20", default-features = false }
panic-persist = { version = "0.3.0", features = ["utf8"] }
picoserve = { path = "../..", features = ["embassy"] }
portable-atomic = { version = "1.6.0", features = ["critical-section"], default-features = false }
rand = { version = "0.8.5", default-features = false }
static_cell = { version = "2.0.0", features = ["nightly"] }
